name: nocodb
description: com.enm10k.nocodb

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: any
  stack_trace: any
  flutter_riverpod:
  flutter_hooks:
  hooks_riverpod:
  intl:
  http:
  data_table_2:
  simple_logger:
  loader_overlay:
  badges:
  flash:
  freezed_annotation:
  riverpod_annotation:
  shared_preferences:
  flutter_secure_storage:
  go_router:
  easy_debounce:
  jiffy:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:
  json_serializable:
  riverpod_generator:
  go_router_builder:

flutter:
  uses-material-design: true